### ISSUE TITLE
impossible to add song to playlist when it was sent via link

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#145] opened 2012-06-10 20:58 UTC
When a friend sends me a link to a track on Youtify, for instance http://www.youtify.com/tracks/youtube/q7C3slwCNsE, it is impossible to add the song to a playlist. It just gets shown in the controls below and in the video part, but there is nothing to drag to a playlist or no other option.

As a resolution, maybe the song should be shown in the play queue and the play queue should also be automatically openend. Currently the toplist shows.

**Comment by pthulin** [comment] 2012-06-22 16:57
Duplicate of #98

Good idea about showing the play queue.

**Closed as completed by pthulin** 2012-06-22 16:57 UTC
