### ISSUE TITLE
some Flattr links not captioned in news feed

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#182] opened 2012-07-17 20:09 UTC
For the news feed, some bare Flattr links show up:
»Per Thulin flattred https://flattr.com/t/741681 41 minutes ago«

Instead, they should be displayed with the artist and song title, just linking to the Flattr page.

**Comment by pthulin** [comment] 2012-07-18 08:35
Duplicate of #150 (fixed yesterday :))

**Closed as completed by pthulin** 2012-07-18 08:35 UTC
